DROP DATABASE IF EXISTS join_us;
CREATE DATABASE join_us;
USE join_us;

CREATE TABLE members (
	email VARCHAR(255) PRIMARY KEY,
	first_name VARCHAR(255), 
	gender VARCHAR(255) NOT NULL,
	age INT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);

